name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: [ubuntu-latest,self-hosted]

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v4

      - name: Créer fichier .env
        run: |
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
          echo "MONGODB_HOST=${{ secrets.MONGODB_HOST }}" >> .env
          echo "MONGODB_PORT=${{ secrets.MONGODB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Démarrer le conteneur
        run: |
          docker network create labo01-network
          docker compose up -d

      - name: Attendre MySQL
        run: |
          sleep 10
          timeout=60
          until docker exec mysql mysqladmin ping -h localhost -u root -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 3
            timeout=$((timeout - 3))
            if [ $timeout -le 0 ]; then
              echo "MySQL failed to start"
              exit 1
            fi
          done
          sleep 5

      - name: Attendre MongoDB
        run: |
          timeout=60
          until docker exec mongo mongosh --eval "db.runCommand({ ping: 1 })" >/dev/null 2>&1; do
            echo "Waiting for MongoDB..."
            sleep 3
            timeout=$((timeout - 3))
            if [ $timeout -le 0 ]; then
              echo "MongoDB failed to start"
              exit 1
            fi
          done
          echo "MongoDB is ready"

      - name: Éxécuter les tests
        run: docker exec store_manager_cli pytest
      
      - name: Cleanup
        if: always()
        run: docker compose down -v